services:
  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    container_name: prompt-management-db
    environment:
      POSTGRES_DB: prompt_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5500:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Blue App Instance
  prompt-manager-blue:
    build: .
    container_name: prompt-manager-blue
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "deployment=blue"

  # Green App Instance
  prompt-manager-green:
    build: .
    container_name: prompt-manager-green
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "deployment=green"
    profiles:
      - green

  # Nginx Load Balancer for Blue-Green Deployment
  nginx:
    image: nginx:alpine
    container_name: prompt-management-nginx
    ports:
      - "3060:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-blue.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - prompt-manager-blue
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge
