// Permission constants based on the schema
export const PERMISSIONS = {
  MANAGE_USERS: "MANAGE_USERS",
  MANAGE_USER_ROLES: "MANAGE_USER_ROLES",
  VIEW_PROMPTS: "VIEW_PROMPTS",
  CREATE_PROMPTS: "CREATE_PROMPTS",
  EDIT_PROMPTS: "EDIT_PROMPTS",
  DELETE_PROMPTS: "DELETE_PROMPTS",
  MANAGE_SYSTEM: "MANAGE_SYSTEM",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

// Default permissions for each role
export const ROLE_PERMISSIONS = {
  Owner: [
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_USER_ROLES,
    PERMISSIONS.VIEW_PROMPTS,
    PERMISSIONS.CREATE_PROMPTS,
    PERMISSIONS.EDIT_PROMPTS,
    PERMISSIONS.DELETE_PROMPTS,
    PERMISSIONS.MANAGE_SYSTEM,
  ],
  Admin: [PERMISSIONS.VIEW_PROMPTS],
  Developer: [
    PERMISSIONS.VIEW_PROMPTS,
    PERMISSIONS.CREATE_PROMPTS,
    PERMISSIONS.EDIT_PROMPTS,
    PERMISSIONS.DELETE_PROMPTS,
  ],
} as const;

export type Role = "Owner" | "Admin" | "Developer";
